### ISSUE TITLE
Add other AsyncIterator type parameters to HAsyncIterator

### ISSUE THREAD

**Issue by GerkinDev** [alkihis/iterator-helper#4]
Hi, first, thank you for that great utility that allows to do a real use of iterators in javascript.

I have created an iterator that fetch a list of DB documents, and I want to be able to close it early. For this, I've added a special value `dispose` I can call `next` with, that actually closes the aggregation.

```ts
export async function* aggregationAsAsyncIterator<T>( aggregationCursor: AggregationCursor<T> ): AsyncIterator<T, void, 'dispose' | undefined> {
	let item: T | undefined;
	let dispose: 'dispose' | undefined;
	do {
		item = await aggregationCursor.next();
		if( item ){
			dispose = yield item;
		}
	} while( item && dispose !== 'dispose' );
	return aggregationCursor.close();
}
```

Unfortunatelly, when I wrap this iterator in `aiter`, the `next` type is lost, so my IDE don't know how to deal with it.

Any advices on how I can come around this issue ? Or could you project `AsyncIterator`'s `TNext` in `HAsyncIterator` ?

Have a nice day, :beers: cheers !

**Comment by alkihis** [comment]
Hi, thank you for your interest in this project.
I just push a new version on npm that support `TNext` and `TReturn` types for both sync and async wrapped iterators.

Type-checking with `TNext` should now works fine.
Have a nice day.

**Comment by GerkinDev** [comment]
Wow. You rocks so hard. Thank you ! :beers:
