### ISSUE TITLE
Polyfill

### ISSUE THREAD

**Issue by piranna** [alkihis/iterator-helper#5]
How can this project be registered on global objects as a polyfill instead of as a wrapper ponyfill?

**Comment by alkihis** [comment]
Take a look to https://github.com/alkihis/iterator-polyfill !

**Comment by piranna** [comment]
Oh great, thanks :-D Maybe we should add a link to that repo in the readme :-)

Related question: how much different is this implementation from other ones like `core-js`?

**Comment by alkihis** [comment]
It is an unofficial polyfill with unspecified added features of the ECMA proposals 😄 
If you need to be 100% spec-future-compatible, use the core-js one for sure!

**Comment by piranna** [comment]
Great, thank you for the clarification :-) Yes, I was targeting a 100% spec compatible, but maybe the extra ones can be moved to a helpers module :-D
